name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch Packages
      uses: geowatson/flutter-latest@1.0.0
      with:
        args: pub get

    - name: Run Tests
      uses: geowatson/flutter-latest@1.0.0
      with:
        args: test
